### ISSUE TITLE
Extraction failed: site name issues

### ISSUE THREAD

**Issue by lukefullard** [mullenkamp/hilltop-py#4]
Hi, I'm having issues with the get_data() command.
Python version: 3.6.13
Running on a new conda environment.

site_list( )  works as expected.
measurement_list( ) works as expected.

Example code:

```
import requests
import pandas as pd
from hilltoppy import hilltop

hts = (directory of my hts file)
mysites = ['Whanganui at d/s Taumarunui STP']
mymtypes = ['Nitrate (HRC) [Nitrate (HRC)]']
tsdata = hilltop.get_data(hts, mtypes=mymtypes, sites = mysites)
```

Which fails with the following output:
"Extraction failed for site Whanganui at d/s Taumarunui STP and mtype Nitrate (HRC) [Nitrate (HRC)]"

If I now run the example code below (without supplying a site name):

```
import requests
import pandas as pd
from hilltoppy import hilltop

hts = (directory of my hts file)
mysites = ['Whanganui at d/s Taumarunui STP']
mymtypes = ['Nitrate (HRC) [Nitrate (HRC)]']
tsdata = hilltop.get_data(hts, mtypes=mymtypes)
```

Then the error becomes

Name: Measurement, Length: 188, dtype: object
<class 'pandas.core.series.Series'> returned a result with an error set
Extraction failed for site 17  

followed by a list of all sites names in the hts file.

Could you please guide me, where am I going wrong?
Thanks.

**Comment by mullenkamp** [comment]
Hi Luke,

I'm glad that the site_list and measurement_list functions still work well. I've personally always had trouble with the Hilltop.pyd methods to work properly ;)
The output of your first result would seem to indicate that the combination of that site and mtype doesn't exist. You'll definitely always need to pass both sites and mtypes parameters to the get_data function .
I can no longer test the COM or Hilltop.pyd methods as I don't work at ECan anymore. 

What I would recommend is that you use the Hilltop web service functions [hilltop-py](https://hilltop-py.readthedocs.io/en/latest/usage.html#web-service). It's more reliable, straightforward to use and test, and I'm still maintaining it (since I still get data from Hilltop servers as an external person).
Since you're at Horizon RC, you should be able to use the hilltop endpoint/base_url of https://hilltopserver.horizons.govt.nz/data.hts to access your data. I'm guessing there are other "hts file" links, but you'll have to check the hilltopsystem.dsn in the root folder of your Hilltop installation to find out.

**Comment by lukefullard** [comment]
Thank you very much for the advice.
The web service function looks like it would be a good option. Sounds like a good job for Monday!
Thank you!
