### ISSUE TITLE
get_data_quality erroring for start date in com

### ISSUE THREAD

**Issue by ECAN-EmilyG** [mullenkamp/hilltop-py#54]
Hi Mike,

Been trying to use the get_data_quality function in Hilltop-py COM but the parameter "start" doesn't seem to work unless you put in a date (which doesn't seem to be a requirement). 
The error seems to be around "DataStartTime". 
  _File ~\Miniconda3_32bit\lib\site-packages\hilltoppy\com.py:290 in get_data_quality
    start1 = wqr.DataStartTime_
If I run first with a start date and then remove it and re-run, the file will pull the full record date record which is weird. If I start from a fresh console it will fail. 

Another observation is the doc string requires ISO format but will also error if I put the time in. 
_start : str
        The start date to retreive from the data in ISO format (e.g. '2011-11-30 00:00')._

Thanks!
Emily

**Comment by mullenkamp** [comment]
Hi Emily. 
Is there any possibility that you can use the web_service module instead of the COM module?
Though I'm impressed you're still able to use the COM module ;)
You seem to be using it correctly, but it will be really hard (if not impossible) for me to debug the COM module since I don't have a Hilltop server installed.
I've recently improved the web_service module, so it should be even more straightforward to get data using it now. One get_data function to rule them all!

**Comment by ECAN-EmilyG** [comment]
Hi Mike,

We are trying to work with a file we don't want to be exposed through Hilltop Server because it's not been QA-ed yet. We could use the web_service but I am hesitant to create an API as it's "raw" and I don't want others to access it.

I think it all works still - we've been learning a bit more to try and get data from python to Hilltop with some data clean-ups but that's still a work in progress. I guess it's a bit hard to upkeep this function when you don't have the software, so I'll note that as a limitation with COM. 

I'll have a look at the updates to get_data! I've been using python a heap more - even written a little function now called get_parameters.

**Comment by mullenkamp** [comment]
It's good to hear you're working with Python a lot more!
You can always just expose it through the Hilltop server and give it some obscure name that no one is likely to randomly stumble across. Because unless you know the "hts" name, then users don't know it's there. I've actually been recently talking to other RCs to find out some of the "hts" names so that I can get their data ;)
