### ISSUE TITLE
horizons error not .hts

### ISSUE THREAD

**Issue by DAGerretzen** [mullenkamp/hilltop-py#64]
Hi Mike,

I've been attempting to use the package to pull data from the horizons hilltop server - https://envirodata.horizons.govt.nz/api/hilltop/data?

However it's failing due to the below as it doesn't go to an .hts file - can we get a workaround put in for this?

if not hts.endswith('.hts'):
    raise ValueError('The hts file must end with .hts')

Cheers,
Darren

**Comment by mullenkamp** [comment]
Hi Darren,

I'm glad your using the package. 
Based on the link you provided, you probably want to assign these variables for your input:
`base_url = https://envirodata.horizons.govt.nz/api/hilltop/`
`hts = data.hts`

You can read further about the data access methods and associated inputs here:
https://hilltop-py.readthedocs.io/en/latest/usage_v1.html#data-access

Let me know if that solves your problem or not.

**Comment by mullenkamp** [comment]
On a further look, I better see what you mean...I've never come across a Hilltop server instance that didn't use the .hts as part of the url. How can the Hilltop server be set up as to not require the .hts? Is it some proxy server link?

**Comment by DAGerretzen** [comment]
Thanks for having a look so quickly Mike

Yeah I'm not too sure how they have set it up..

I just commented out the .hts check and it all worked from from there, not sure if that's what you want for a long term solution though

**Comment by mullenkamp** [comment]
Yeah, it's a very easy fix, so as you said that's not really the issue.
It's not that big of a deal to me to remove that check. That's because I've recently heavily reworked all of the code for the web_service module and I've also created a new dedicated Hilltop class that I will be primarily using going forward. I will still maintain the existing web_service module, but the Hilltop class will be able to do proper checks to see if the Hilltop server link produces an http response (rather than resorting to the .hts check).

**Comment by mullenkamp** [comment]
Updated in #72
